version: '3'

services:
  websocket-server:
    image: node:latest
    container_name: websocket-server
    restart: always
    working_dir: /app
    volumes:
      - ./src/server:/app
    ports:
      - "3003:3003"
    command: node .

  frontend:
    image: nginx:latest
    container_name: frontend
    restart: always
    volumes:
      - ./src/dist:/usr/share/nginx/html
    ports:
      - "8083:80"
    depends_on:
      - websocket-server